apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aqua-db-pvc
  namespace: aqua
spec:
  storageClassName: aqua-storage
  volumeMode: Filesystem
  volumeName: aquadb-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
